import { AnimatePresence, motion } from "framer-motion";
import { Cpu, Sparkles } from "lucide-react";
import { useState } from "react";

type Shape = "markdown" | "thoughtform" | "vector";
const SHAPES: Shape[] = ["markdown", "thoughtform", "vector"];

const FROM_VECTOR = "Off by default. An LLM through AgentVault (POLYTICIAN_LLM_PROVIDER=agentvault, origin llm), given neighbours from the concept's own namespace. A vector can't be decoded back into text.";

/** From polytician's README: which conversions derive (null), which generate, and which can do either. */
const GENERATED: Record<string, { either: boolean; text: string } | null> = {
  "thoughtform→vector": null,
  "thoughtform→markdown": null,
  "markdown→vector": null,
  "markdown→thoughtform": {
    either: true,
    text: "Off by default; turn on one: an LLM through AgentVault (POLYTICIAN_LLM_PROVIDER=agentvault, origin llm), or the rule-based NLP pipeline (POLYTICIAN_NLP_PIPELINE=rule-based, origin derived, no LLM).",
  },
  "vector→markdown": { either: false, text: FROM_VECTOR },
  "vector→thoughtform": { either: false, text: FROM_VECTOR },
};

/** Click a cell: is that conversion derived locally, generated by a model, or either, as configured? */
export function ConversionMatrix() {
  const [cell, setCell] = useState<[Shape, Shape]>(["markdown", "vector"]);
  const key = `${cell[0]}→${cell[1]}`;
  const gen = GENERATED[key];

  return (
    <div className="grid md:grid-cols-[auto_1fr] gap-6 sm:gap-10 items-center max-w-4xl mx-auto">
      <div className="overflow-x-auto">
        <table className="font-mono text-xs sm:text-sm border-separate border-spacing-1.5 mx-auto">
          <thead>
            <tr>
              <th className="text-muted-foreground font-normal text-right pr-2">from ╲ to</th>
              {SHAPES.map((s) => (
                <th key={s} className="text-muted-foreground font-normal px-1">{s}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {SHAPES.map((from) => (
              <tr key={from}>
                <th className="text-muted-foreground font-normal text-right pr-2">{from}</th>
                {SHAPES.map((to) => {
                  if (from === to) return <td key={to} className="text-center text-white/15">·</td>;
                  const k = `${from}→${to}`;
                  const selected = k === key;
                  const g = GENERATED[k];
                  return (
                    <td key={to}>
                      <button
                        onClick={() => setCell([from, to])}
                        aria-label={k}
                        className={`w-full h-12 sm:h-14 rounded-xl border grid place-items-center transition-all cursor-pointer ${
                          selected
                            ? "border-primary bg-primary/15 scale-105"
                            : "border-white/10 bg-white/[0.03] hover:border-white/25"
                        }`}
                      >
                        {g ? (
                          <span className="flex gap-1">
                            <Sparkles className="w-4 h-4 text-primary" />
                            {g.either && <Cpu className="w-4 h-4 text-green-400" />}
                          </span>
                        ) : (
                          <Cpu className="w-4 h-4 text-green-400" />
                        )}
                      </button>
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <AnimatePresence mode="wait">
        <motion.div
          key={key}
          initial={{ opacity: 0, x: 8 }}
          animate={{ opacity: 1, x: 0 }}
          exit={{ opacity: 0, x: -8 }}
          transition={{ duration: 0.2 }}
          className="space-y-3"
        >
          <p className="font-mono text-lg text-white">
            convert_concept <span className="text-primary">{cell[0]}</span> → <span className="text-primary">{cell[1]}</span>
          </p>
          {gen ? (
            <>
              <p className="flex items-center gap-2 font-semibold text-primary">
                <Sparkles className="w-4 h-4" />
                {gen.either && <Cpu className="w-4 h-4 text-green-400" />}
                {gen.either ? "Generated or derived" : "Generated"}
              </p>
              <p className="text-muted-foreground break-words">{gen.text}</p>
            </>
          ) : (
            <>
              <p className="flex items-center gap-2 font-semibold text-green-400"><Cpu className="w-4 h-4" /> Derived</p>
              <p className="text-muted-foreground">
                {cell[1] === "vector" ? "The embedding model, in-process." : "A fixed template, in-process."} No LLM, no API key. Origin derived.
              </p>
            </>
          )}
          <p className="text-xs text-muted-foreground">
            Never replaces content a caller wrote or imported unless you pass <span className="font-mono text-white/80">overwrite: true</span>. Otherwise: <span className="font-mono text-white/80">OVERWRITE_REFUSED</span>.
          </p>
        </motion.div>
      </AnimatePresence>
    </div>
  );
}
