import { AnimatePresence, motion } from "framer-motion";
import { Cpu, Sparkles } from "lucide-react";
import { useState } from "react";

type Shape = "markdown" | "thoughtform" | "vector";
const SHAPES: Shape[] = ["markdown", "thoughtform", "vector"];

/** From polytician's README: which conversions derive and which generate. */
const NEEDS_LLM: Record<string, string | null> = {
  "thoughtform→vector": null,
  "thoughtform→markdown": null,
  "markdown→vector": null,
  "markdown→thoughtform": "Your LLM, or the rule-based NLP pipeline.",
  "vector→markdown": "Your LLM: Anthropic, OpenAI, MCP sampling, or AgentVault.",
  "vector→thoughtform": "Your LLM: Anthropic, OpenAI, MCP sampling, or AgentVault.",
};

/** Click a cell: is that conversion derived locally, or generated by a model? */
export function ConversionMatrix() {
  const [cell, setCell] = useState<[Shape, Shape]>(["markdown", "vector"]);
  const key = `${cell[0]}→${cell[1]}`;
  const llm = NEEDS_LLM[key];

  return (
    <div className="grid md:grid-cols-[auto_1fr] gap-6 sm:gap-10 items-center max-w-4xl mx-auto">
      <div className="overflow-x-auto">
        <table className="font-mono text-xs sm:text-sm border-separate border-spacing-1.5 mx-auto">
          <thead>
            <tr>
              <th className="text-muted-foreground font-normal text-right pr-2">from ╲ to</th>
              {SHAPES.map((s) => (
                <th key={s} className="text-muted-foreground font-normal px-1">{s}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {SHAPES.map((from) => (
              <tr key={from}>
                <th className="text-muted-foreground font-normal text-right pr-2">{from}</th>
                {SHAPES.map((to) => {
                  if (from === to) return <td key={to} className="text-center text-white/15">·</td>;
                  const k = `${from}→${to}`;
                  const selected = k === key;
                  const gen = NEEDS_LLM[k] !== null;
                  return (
                    <td key={to}>
                      <button
                        onClick={() => setCell([from, to])}
                        aria-label={k}
                        className={`w-full h-12 sm:h-14 rounded-xl border grid place-items-center transition-all cursor-pointer ${
                          selected
                            ? "border-primary bg-primary/15 scale-105"
                            : "border-white/10 bg-white/[0.03] hover:border-white/25"
                        }`}
                      >
                        {gen ? <Sparkles className="w-4 h-4 text-primary" /> : <Cpu className="w-4 h-4 text-green-400" />}
                      </button>
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <AnimatePresence mode="wait">
        <motion.div
          key={key}
          initial={{ opacity: 0, x: 8 }}
          animate={{ opacity: 1, x: 0 }}
          exit={{ opacity: 0, x: -8 }}
          transition={{ duration: 0.2 }}
          className="space-y-3"
        >
          <p className="font-mono text-lg text-white">
            convert_concept <span className="text-primary">{cell[0]}</span> → <span className="text-primary">{cell[1]}</span>
          </p>
          {llm ? (
            <>
              <p className="flex items-center gap-2 font-semibold text-primary"><Sparkles className="w-4 h-4" /> Generated</p>
              <p className="text-muted-foreground">{llm}</p>
            </>
          ) : (
            <>
              <p className="flex items-center gap-2 font-semibold text-green-400"><Cpu className="w-4 h-4" /> Derived, deterministic</p>
              <p className="text-muted-foreground">Runs in-process. No model call, no key.</p>
            </>
          )}
        </motion.div>
      </AnimatePresence>
    </div>
  );
}
